---

- name: Download docker setup script for desired version
  get_url:
    url: "{{ setup_script_url }}"
    dest: "/tmp/docker-setup.sh"
    checksum: "{{ setup_script_checksum|default(omit) }}"
    mode: 0755

- name: Execute docker setup script
  shell: "/tmp/docker-setup.sh"
