---

- include: "os/{{ ansible_os_family }}.yml"

- name: check if docker is installed
  command: which dockerd
  register: which_dockerd
  changed_when: False
  ignore_errors: yes

- include: "install.yml"
  when: (which_dockerd | failed)

- name: ensure config folder is present
  file:
    path: /etc/docker
    state: directory

- name: ensure docker-py module is installed
  pip:
    name: docker-py
    version: 1.9.0
  when: dockerpy

- meta: flush_handlers

- name: ensure starts on system boot
  service:
    name: docker
    enabled: yes